services:
  - type: web
    name: fastapi-app
    env: python
    plan: free   # or starter/pro, depending on your account
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
